CREATE TABLE user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_id BIGINT NULL,
    type VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    notification_key VARCHAR(120) NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_notifications_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_notifications_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT uk_user_notifications_user_key UNIQUE (user_id, notification_key)
);

CREATE INDEX idx_user_notifications_user_created ON user_notifications(user_id, created_at);
CREATE INDEX idx_user_notifications_user_read ON user_notifications(user_id, is_read);
