CREATE TABLE order_complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_order_complaints_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_complaints_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_order_complaints_order_user UNIQUE (order_id, user_id)
);

CREATE INDEX idx_order_complaints_order ON order_complaints(order_id);
CREATE INDEX idx_order_complaints_user ON order_complaints(user_id);
CREATE INDEX idx_order_complaints_status_created ON order_complaints(status, created_at);

CREATE TABLE order_complaint_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    missing_quantity INTEGER NOT NULL CHECK (missing_quantity > 0),
    CONSTRAINT fk_order_complaint_items_complaint FOREIGN KEY (complaint_id)
        REFERENCES order_complaints(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_complaint_items_order_item FOREIGN KEY (order_item_id)
        REFERENCES order_items(id) ON DELETE CASCADE,
    CONSTRAINT uk_order_complaint_items_complaint_item UNIQUE (complaint_id, order_item_id)
);

CREATE INDEX idx_order_complaint_items_complaint ON order_complaint_items(complaint_id);
CREATE INDEX idx_order_complaint_items_order_item ON order_complaint_items(order_item_id);

CREATE TABLE order_complaint_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_complaint_images_complaint FOREIGN KEY (complaint_id)
        REFERENCES order_complaints(id) ON DELETE CASCADE
);

CREATE INDEX idx_order_complaint_images_complaint ON order_complaint_images(complaint_id);
