CREATE TABLE IF NOT EXISTS order_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    contract_number VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(25) NOT NULL DEFAULT 'DRAFT',
    quality_terms TEXT,
    cancel_terms TEXT,
    extra_notes TEXT,
    confirmed_at TIMESTAMP,
    confirmed_by BIGINT,
    confirmed_ip VARCHAR(45),
    rejected_at TIMESTAMP,
    rejection_reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contract_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_contract_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_order_contracts_order_id ON order_contracts(order_id);
CREATE INDEX IF NOT EXISTS idx_order_contracts_status ON order_contracts(status);

CREATE TABLE IF NOT EXISTS payment_milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    milestone_order INT NOT NULL,
    milestone_name VARCHAR(100) NOT NULL,
    percentage DECIMAL(5,2) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    due_date DATE,
    payment_qr_url VARCHAR(500),
    paid_at TIMESTAMP,
    transaction_ref VARCHAR(100),
    paid_amount DECIMAL(15,2),
    verified_at TIMESTAMP,
    verified_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_milestone_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_milestone_verified_by FOREIGN KEY (verified_by) REFERENCES users(id),
    CONSTRAINT uk_payment_milestones_order_step UNIQUE (order_id, milestone_order)
);

CREATE INDEX IF NOT EXISTS idx_payment_milestones_order_id ON payment_milestones(order_id);
CREATE INDEX IF NOT EXISTS idx_payment_milestones_status_due_date ON payment_milestones(status, due_date);

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS payment_deadline DATE;
