-- Add new columns for order_complaints
ALTER TABLE order_complaints ADD COLUMN complaint_type VARCHAR(50) NOT NULL DEFAULT 'MISSING_ITEM';
ALTER TABLE order_complaints ADD COLUMN admin_note TEXT;

-- Update order_complaint_items to support defective items
ALTER TABLE order_complaint_items DROP CONSTRAINT IF EXISTS order_complaint_items_missing_quantity_check;
ALTER TABLE order_complaint_items ALTER COLUMN missing_quantity DROP NOT NULL;
ALTER TABLE order_complaint_items ALTER COLUMN missing_quantity SET DEFAULT 0;

ALTER TABLE order_complaint_items ADD COLUMN defective_quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE order_complaint_items ADD COLUMN reason_note TEXT;

-- Add a new constraint ensuring at least one of the quantities is positive
ALTER TABLE order_complaint_items ADD CONSTRAINT chk_complaint_quantity 
    CHECK (COALESCE(missing_quantity, 0) > 0 OR defective_quantity > 0);

-- Create history table to track complaint progression and discussion
CREATE TABLE order_complaint_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT NOT NULL,
    action_by_user_id BIGINT,
    action_type VARCHAR(50) NOT NULL,  -- e.g., CREATED, UPDATED, STATUS_CHANGED, ADMIN_REPLY
    old_status VARCHAR(20),
    new_status VARCHAR(20),
    note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_complaint_history_complaint FOREIGN KEY (complaint_id) REFERENCES order_complaints(id) ON DELETE CASCADE
);
CREATE INDEX idx_order_complaint_history_complaint ON order_complaint_history(complaint_id);
